name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

            # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    
          # Step 3: Build Docker Image
      - name: Build Docker Image
        run: docker build -t docker.io/${{ secrets.DOCKER_USERNAME }}/flaskapp:latest .
    
          # Step 4: Push Docker Image to Docker Hub
      - name: Push Docker Image
        run: docker push docker.io/${{ secrets.DOCKER_USERNAME }}/flaskapp:latest

         # Step 5: Trigger Render Deployment (optional, using Deploy Hook)
      - name: Trigger Render Deployment
        run: curl -X POST -d '{}' "https://api.render.com/v1/deploy/${{ secrets.RENDER_DEPLOY_HOOK }}"